services:
  web:
    build: .
    container_name: nexus_app
    ports:
      - "8080:80"
    volumes:
      - ./nexus:/var/www/html/nexus
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: nexus_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nexus_db
      MYSQL_USER: nexus
      MYSQL_PASSWORD: nexus123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
